#Script to deploy on the Render cloud platform
name: Node.js CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
     -uses: actions/checkout@v2
     -name: invoke deploment hook
     -uses: distributhor/workflow-webhook@v2
     env:
      webhook_url: ${{secretes.DEPLOY_HOOK_URL}}
      webhook_secrete: ${{secretes.DEPLOY_HOOK_KEY}}
    -uses: bounceapp/render-actions@0.6.0
  with:
    render token: ${{secrets. RENDER _API_KEY}}
    github-token: ${{secrets. ACC_API_KEY}} # This is the GitHub token
    service-id: "srv-cg901tg2qv259v98ulkg" # This id is unique for each app
    retries: 20
    wait: 16000
    sleep: 30000
